-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.Swapi.Object.Species exposing (..)

import Gql.Swapi.InputObject
import Gql.Swapi.Interface
import Gql.Swapi.Object
import Gql.Swapi.Scalar
import Gql.Swapi.ScalarCodecs
import Gql.Swapi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The name of this species.
-}
name : SelectionSet (Maybe String) Gql.Swapi.Object.Species
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| The classification of this species, such as "mammal" or "reptile".
-}
classification : SelectionSet (Maybe String) Gql.Swapi.Object.Species
classification =
    Object.selectionForField "(Maybe String)" "classification" [] (Decode.string |> Decode.nullable)


{-| The designation of this species, such as "sentient".
-}
designation : SelectionSet (Maybe String) Gql.Swapi.Object.Species
designation =
    Object.selectionForField "(Maybe String)" "designation" [] (Decode.string |> Decode.nullable)


{-| The average height of this species in centimeters.
-}
averageHeight : SelectionSet (Maybe Float) Gql.Swapi.Object.Species
averageHeight =
    Object.selectionForField "(Maybe Float)" "averageHeight" [] (Decode.float |> Decode.nullable)


{-| The average lifespan of this species in years, null if unknown.
-}
averageLifespan : SelectionSet (Maybe Int) Gql.Swapi.Object.Species
averageLifespan =
    Object.selectionForField "(Maybe Int)" "averageLifespan" [] (Decode.int |> Decode.nullable)


{-| Common eye colors for this species, null if this species does not typically
have eyes.
-}
eyeColors : SelectionSet (Maybe (List (Maybe String))) Gql.Swapi.Object.Species
eyeColors =
    Object.selectionForField "(Maybe (List (Maybe String)))" "eyeColors" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| Common hair colors for this species, null if this species does not typically
have hair.
-}
hairColors : SelectionSet (Maybe (List (Maybe String))) Gql.Swapi.Object.Species
hairColors =
    Object.selectionForField "(Maybe (List (Maybe String)))" "hairColors" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| Common skin colors for this species, null if this species does not typically
have skin.
-}
skinColors : SelectionSet (Maybe (List (Maybe String))) Gql.Swapi.Object.Species
skinColors =
    Object.selectionForField "(Maybe (List (Maybe String)))" "skinColors" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| The language commonly spoken by this species.
-}
language : SelectionSet (Maybe String) Gql.Swapi.Object.Species
language =
    Object.selectionForField "(Maybe String)" "language" [] (Decode.string |> Decode.nullable)


{-| A planet that this species originates from.
-}
homeworld :
    SelectionSet decodesTo Gql.Swapi.Object.Planet
    -> SelectionSet (Maybe decodesTo) Gql.Swapi.Object.Species
homeworld object_ =
    Object.selectionForCompositeField "homeworld" [] object_ (identity >> Decode.nullable)


type alias PersonConnectionOptionalArguments =
    { after : OptionalArgument String
    , first : OptionalArgument Int
    , before : OptionalArgument String
    , last : OptionalArgument Int
    }


personConnection :
    (PersonConnectionOptionalArguments -> PersonConnectionOptionalArguments)
    -> SelectionSet decodesTo Gql.Swapi.Object.SpeciesPeopleConnection
    -> SelectionSet (Maybe decodesTo) Gql.Swapi.Object.Species
personConnection fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { after = Absent, first = Absent, before = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "personConnection" optionalArgs object_ (identity >> Decode.nullable)


type alias FilmConnectionOptionalArguments =
    { after : OptionalArgument String
    , first : OptionalArgument Int
    , before : OptionalArgument String
    , last : OptionalArgument Int
    }


filmConnection :
    (FilmConnectionOptionalArguments -> FilmConnectionOptionalArguments)
    -> SelectionSet decodesTo Gql.Swapi.Object.SpeciesFilmsConnection
    -> SelectionSet (Maybe decodesTo) Gql.Swapi.Object.Species
filmConnection fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { after = Absent, first = Absent, before = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "filmConnection" optionalArgs object_ (identity >> Decode.nullable)


{-| The ISO 8601 date format of the time that this resource was created.
-}
created : SelectionSet (Maybe String) Gql.Swapi.Object.Species
created =
    Object.selectionForField "(Maybe String)" "created" [] (Decode.string |> Decode.nullable)


{-| The ISO 8601 date format of the time that this resource was edited.
-}
edited : SelectionSet (Maybe String) Gql.Swapi.Object.Species
edited =
    Object.selectionForField "(Maybe String)" "edited" [] (Decode.string |> Decode.nullable)


{-| The ID of an object
-}
id : SelectionSet Gql.Swapi.ScalarCodecs.Id Gql.Swapi.Object.Species
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Gql.Swapi.ScalarCodecs.codecs |> Gql.Swapi.Scalar.unwrapCodecs |> .codecId |> .decoder)
