-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gql.Swapi.ScalarCodecs exposing (..)

import Gql.Swapi.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Gql.Swapi.Scalar.Id


codecs : Gql.Swapi.Scalar.Codecs Id
codecs =
    Gql.Swapi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
